name: KEEPALIVE

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes.

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        path: sync-repo

    - name: check against the commit ID
      run: |
        cd sync-repo
        date > keepalive.txt
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add keepalive.txt
        git commit -m "Update"
        git push origin main
