name: SYNC REPO

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour.

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        path: sync-repo

    - name: use SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - uses: actions/cache@v4
      id: repo-cache
      with:
        path: .
        key: linux

    - name: clone repo
      if: steps.repo-cache.outputs.cache-hit != 'true'
      run: |
        git clone -v git://git.kernel.org/pub/scm/linux/kernel/git/akpm/mm

    - name: sync linux repo
      run: |        
        cd mm
        git checkout master
        if git rev-parse --verify mm-unstable >/dev/null 2>&1; then
            git branch -D mm-unstable
        fi
        git checkout master && git pull
        git checkout mm-stable && git pull
        git checkout mm-unstable && git pull
        git push -f --all git@github.com:ioworker0/linux.git
      
    - name: check against the commit ID
      run: |
        cd sync-repo
        date > hello_world.txt
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add hello_world.txt
        git commit -m "Update hello_world.txt"
        git push origin main
