name: SYNC REPO MAN

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        path: sync-repo

    - name: use SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: clone repo
      run: |
        git clone -v git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux

    - name: sync linux repo
      run: |        
        cd linux
        git checkout master
        git checkout master && git pull
        # 1. 处理 linux-6.6.y 分支
        git checkout linux-6.6.y && git pull  # 拉取远程最新内容（避免冲突）
        git push -f git@github.com:ioworker0/linux.git linux-6.6.y

        # 2. 处理 linux-6.12.y 分支
        git checkout linux-6.12.y && git pull
        git push -f git@github.com:ioworker0/linux.git linux-6.12.y

        # 3. 处理 linux-6.1.y 分支
        git checkout linux-6.1.y && git pull
        git push -f git@github.com:ioworker0/linux.git linux-6.1.y
